library 'buzz-shared-library@master'
def nodePodYaml = libraryResource 'podtemplates/node-pod.yaml'
def kanikoPodYaml = libraryResource 'podtemplates/kaniko-pod.yaml'
def helmKubectlYaml = libraryResource 'podtemplates/helm-kubectl-pod.yaml'
pipeline {
  agent none
  options { 
    buildDiscarder(logRotator(numToKeepStr: '5'))
    skipDefaultCheckout true
  }
  stages {
    stage('Acquiring pod') {
	 agent {
            kubernetes {
                label 'node'
                yaml nodePodYaml
                }
            }	
            stages{
                stage('Install'){
                    steps {
                        container('node') {
                        checkout scm
                        sh 'npm install'
		                //stash includes: 'Dockerfile', name: 'Dockerfile'
                        script{
		                version = sh(returnStdout: true, script: """
                        node -pe "require('./package.json').version" | tr -d '[:space:]'
                        """)
 		                }
                         echo "App Version: ${version}"
                   }

              }
                    }
                
            
            stage('Test'){
                    steps {
                        container('node') {
                        sh 'CI=true npm test'
                    }
                    script{
                   commitHash = sh(returnStdout: true, script: "git rev-parse HEAD | cut -c1-7 | tr -d '\n'")
                 }
            }
            post {
                always {
                   echo "done"     
                }
                }
            }

	    }
        }
        stage('Build Docker Image') {
         agent {
            kubernetes {
                label 'kaniko'
                yaml kanikoPodYaml
                }
            }
            steps {
              container(name: 'kaniko', shell: '/busybox/sh') {
                //unstash 'Dockerfile'
                withEnv(['PATH+EXTRA=/busybox:/kaniko']) {
            	sh """#!/busybox/sh
            	executor \
                -c git://github.com/${repoOwner}/${applicationName}.git \
                -d gcr.io/na-csa-msuarez/${applicationName}:${BUILD_NUMBER} \
                -d gcr.io/na-csa-msuarez/${applicationName}:${version}-${commitHash} \
                -d gcr.io/na-csa-msuarez/${applicationName}:latest
                """
                   }
              }
            }
        }
        stage('Helm install') {
         agent {
            kubernetes {
                label 'helm-kubectl'
                yaml helmKubectlYaml
                }
            }
            steps {
                checkout scm
              container('helm-kubectl') {
                sh "curl -X DELETE http://34.67.152.26:8080/api/charts/${applicationName}/0.0.1"
		            sh "helm package --app-version ${version} ${applicationName} --debug --save=false"
		            sh """curl -L --data-binary "@${applicationName}-0.0.1.tgz" http://34.67.152.26:8080/api/charts"""
		            sh "helm init --client-only"
		            sh "helm repo add chartmuseum http://34.67.152.26:8080"
                sh """helm upgrade ${applicationName} chartmuseum/${applicationName} \
                -i --namespace cje \
                --set image.tag=${version}-${commitHash}"""
                   }
            }
              }
            
        
    }
}
